### ISSUE TITLE
We are not capable of updating a component in React

### ISSUE THREAD

**Issue by DaniBAIG7** [Arquisoft/radarin_en1b#114]
Javier and I have been working on removing locations from the POD. We managed to do it properly, but we are not capable of refreshing the page to make the removed marker disappear. We tried (inside webapp/src/utils/solidAccessing/RemoveLocations.js) to refresh the page with `window.location.reload()`, but it doesn't save the session, so the user has to log in again. We also tried to modify some values inside the function component (inside webapp/src/views/Map.js) to force a re-render, but it doesn't seem to work neither. Help needed :,( .
The code related is inside [this branch](https://github.com/Arquisoft/radarin_en1b/tree/webapplication-location-removal) (in the webapp folder, as stated before).

**Comment by pglez82** [comment]
We never do a window.location.reload in react. You have to work with the state. What I would do is, in the Map component, instead of calling removeUserLocation directly in the onclick, create a function where you call this function but also you refresh the markers array just after deletion (maybe retrieving them again from the pod?). As you are using redux and I never used it, I'm not sure of the exact change but for sure that is the way to go. You need to update this array so the map function is executed again over the markers array and the markers get updated. Always remember that react is listening for state changes and updating your components accordingly, so updating the state is the way to go.

Let me know if that helps.

**Comment by uo269412** [comment]
@DaniBAIG7 and I finally managed to do it. It was key to refresh the state in Redux, this solved the issue and the map now renders accordingly when we remove a location. Thanks for the advices today!
