### ISSUE TITLE
4. Solution Strategy

### ISSUE THREAD

**Issue by UO266499** [Arquisoft/radarin_en1b#21]
A short summary and explanation of the fundamental decisions and solution strategies, that shape the system’s architecture. These include

    - technology decisions
    - decisions about the top-level decomposition of the system, e.g. usage of an architectural pattern or design pattern
    - decisions on how to achieve key quality goals
    - relevant organizational decisions, e.g. selecting a development process or delegating certain tasks to third parties.

Keep the explanation short and concise

**Comment by uo269412** [comment]
### Revision of the documentation prototype

### _Regarding_ 4.1

We should add alternatives, then explaining why are we picking that specific software instead of the others
Think about how to implement the mobile application (using react native, using an application (this allows that a service keeps sending data), hybrid application)
