### ISSUE TITLE
6. Runtime View

### ISSUE THREAD

**Issue by UO266499** [Arquisoft/radarin_en1b#23]
The runtime view describes concrete behavior and interactions of the system’s building blocks in form of scenarios from the following areas:

    - important use cases or features: how do building blocks execute them?
    - interactions at critical external interfaces: how do building blocks cooperate with users and neighboring systems?
    - operation and administration: launch, start-up, stop
    - error and exception scenarios

Remark: The main criterion for the choice of possible scenarios (sequences, workflows) is their architectural relevance. It is not important to describe a large number of scenarios. You should rather document a representative selection.

**Comment by uo269412** [comment]
### Revision of the documentation prototype

### _Regarding_ 6

The diagram must be reestructured due to it being based around diagram 3 which also needs to be changed (user sends to server, server contains locations of different users, the friends of each user are in the pods, the server communicates with the pods to know which locations to retrieve) (this is just a possibility)
